version: '3.1'
services:
  console-task:
    build: ../console-task
    container_name: console-task
    depends_on:
      - db
    environment:
      - POSTGRES_INITDB_ARGS='--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_SQL_INIT_MODE=always

  db:
    image: postgres:14-alpine
    container_name: db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=password