DROP TABLE IF EXISTS purchase, product, customer;

CREATE TABLE IF NOT EXISTS customer
(
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(200) NOT NULL,
    last_name VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS product
(
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    price DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS purchase
(
    purchase_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    volume INTEGER NOT NULL,
    purchase_date TIMESTAMP NOT NULL,
    CONSTRAINT purchase_customer_id_fk
            FOREIGN KEY (customer_id) REFERENCES customer (customer_id) ON DELETE CASCADE,
    CONSTRAINT purchase_product_id_fk
            FOREIGN KEY (product_id) REFERENCES product (product_id) ON DELETE CASCADE
);
